version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      kubernetes:
        patterns: ["k8s.io/*", "sigs.k8s.io/*"]
      go-deps:
        patterns: ["*"]
        exclude-patterns: ["k8s.io/*", "sigs.k8s.io/*"]
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    groups:
      xterm:
        patterns: ["@xterm/*"]
      npm-deps:
        patterns: ["*"]
        exclude-patterns: ["@xterm/*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
